# Generated by Django 3.2 on 2021-05-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_repo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image_repo.models.save_image)),
                ('result', models.JSONField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, max_length=250)),
                ('colors', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
