# Generated by Django 3.2 on 2021-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='colors',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='result',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
